name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run markdown lint
        run: |
         npm install remark-cli remark_preset-lint-consistent
         npx remark . --use remark_preset-lint-consistent --frail
